name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create executable jar
        run: |
          ./package.sh

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: nowsecure-ci
          path: nowsecure-ci
          retention-days: 5

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"